"""
backend/services/export.py

Handles generation of JSON, CSV, and PDF exports from the UploadResponse schema.
"""

import csv
import io
import json
from datetime import datetime
from typing import Any
from fpdf import FPDF
from models.schemas import UploadResponse

VERSION = "0.2.0"

def generate_json_export(data: UploadResponse) -> str:
    """Returns the full JSON with metadata."""
    payload = data.model_dump()
    payload["_export_metadata"] = {
        "insightml_version": VERSION,
        "generated_at": datetime.utcnow().isoformat() + "Z"
    }
    return json.dumps(payload, indent=2)

def generate_csv_export(data: UploadResponse, export_type: str) -> str:
    """Flattens a specific section into a CSV string."""
    output = io.StringIO()
    writer = csv.writer(output)
    
    if export_type == "profile":
        writer.writerow(["Column Name", "Type", "Unique Values", "Missing Percentage", "Mean", "Min", "Max", "Top Categories"])
        for col in data.profile.columns:
            mean_val = col.mean if col.mean is not None else ""
            min_val = col.min if col.min is not None else ""
            max_val = col.max if col.max is not None else ""
            
            top_cats = ""
            if hasattr(col, "top_categories") and col.top_categories:
                # Assuming top_categories is a list of [val, count] if it exists
                # wait, ColumnProfile might not have top_categories in this iteration!
                pass # let's just leave top_cats blank if it doesn't exist
                
            writer.writerow([
                col.name, col.inferred_type, col.unique_count, round(col.missing_percentage, 2),
                mean_val, min_val, max_val, top_cats
            ])
            
    elif export_type == "numerical":
        writer.writerow(["Feature A", "Feature B", "Pearson", "Spearman", "Mutual Information"])
        if data.relationships and data.relationships.pairs:
            for p in data.relationships.pairs:
                writer.writerow([p.feature_a, p.feature_b, p.pearson, p.spearman, p.mutual_information])
                
    elif export_type == "categorical":
        writer.writerow(["Type", "Feature A", "Feature B/Numerical", "Score Metric", "Score Value", "P-Value"])
        if data.categorical:
            for p in data.categorical.cat_cat_pairs:
                writer.writerow(["Cat-Cat", p.feature_a, p.feature_b, "Cramer's V", p.cramers_v, p.p_value])
            for p in data.categorical.cat_num_pairs:
                writer.writerow(["Cat-Num", p.categorical_feature, p.numerical_feature, "Eta-Squared", p.eta_squared, p.p_value])

    elif export_type == "quality":
        writer.writerow(["Severity", "Category", "Issue Title", "Explanation", "Count", "Percentage", "Affected Columns", "Recommendation"])
        if data.quality and data.quality.warnings:
            for w in data.quality.warnings:
                writer.writerow([
                    w.severity, w.category, w.issue_title, w.explanation,
                    w.count, w.percentage, ", ".join(w.affected_columns), w.recommendation
                ])
                
    elif export_type == "insights":
        writer.writerow(["Priority", "Category", "Title", "Summary", "Recommended Action"])
        if data.insights and data.insights.insights:
            for i in data.insights.insights:
                writer.writerow([i.priority, i.category, i.title, i.summary, i.recommended_action])
                
    return output.getvalue()


class PDFReport(FPDF):
    def header(self):
        self.set_font("Helvetica", "B", 18)
        self.set_text_color(15, 23, 42) # slate-900
        self.cell(0, 10, "InsightML Executive Summary", align="L")
        self.ln(15)
        
    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(100, 116, 139) # slate-500
        self.cell(0, 10, f"Page {self.page_no()} | Generated by InsightML v{VERSION}", align="C")

def generate_pdf_export(data: UploadResponse) -> bytes:
    pdf = PDFReport()
    pdf.add_page()
    
    # Base font sizes
    H2 = 14
    BODY = 10
    
    # ── Dataset Overview
    pdf.set_font("Helvetica", "B", H2)
    pdf.cell(0, 8, "Dataset Overview", new_x="LMARGIN", new_y="NEXT")
    
    pdf.set_font("Helvetica", "", BODY)
    pdf.cell(0, 6, f"Filename: {data.filename}", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 6, f"Rows: {data.rows:,}  |  Columns: {data.columns:,}", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 6, f"Generated: {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S')} UTC", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(5)
    
    # ── Smart Insights (Top 5)
    pdf.set_font("Helvetica", "B", H2)
    pdf.cell(0, 8, "Key Insights", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)
    
    if data.insights and data.insights.insights:
        top_insights = data.insights.insights[:5]
        for ins in top_insights:
            pdf.set_font("Helvetica", "B", 11)
            pdf.cell(0, 6, f"[{ins.priority.upper()}] {ins.title}", new_x="LMARGIN", new_y="NEXT")
            pdf.set_font("Helvetica", "", BODY)
            pdf.multi_cell(0, 5, ins.summary, new_x="LMARGIN", new_y="NEXT")
            pdf.set_text_color(71, 85, 105) # slate-600
            pdf.multi_cell(0, 5, f"Recommendation: {ins.recommended_action}", new_x="LMARGIN", new_y="NEXT")
            pdf.set_text_color(0, 0, 0)
            pdf.ln(4)
    else:
        pdf.set_font("Helvetica", "I", BODY)
        pdf.cell(0, 6, "No key insights generated.", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(4)
        
    # ── Data Quality Summary
    pdf.set_font("Helvetica", "B", H2)
    pdf.cell(0, 8, "Data Quality Warnings", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)
    
    if data.quality and data.quality.warnings:
        # Show top 5 warnings
        top_warns = data.quality.warnings[:5]
        for w in top_warns:
            pdf.set_font("Helvetica", "B", BODY)
            pdf.cell(0, 6, f"{w.severity}: {w.issue_title}", new_x="LMARGIN", new_y="NEXT")
            pdf.set_font("Helvetica", "", BODY)
            pdf.multi_cell(0, 5, w.explanation, new_x="LMARGIN", new_y="NEXT")
            if w.affected_columns:
                pdf.multi_cell(0, 5, f"Columns: {', '.join(w.affected_columns)}", new_x="LMARGIN", new_y="NEXT")
            pdf.ln(2)
        if len(data.quality.warnings) > 5:
            pdf.set_font("Helvetica", "I", 9)
            pdf.cell(0, 5, f"...and {len(data.quality.warnings) - 5} more issues.", new_x="LMARGIN", new_y="NEXT")
    else:
        pdf.set_font("Helvetica", "I", BODY)
        pdf.cell(0, 6, "Dataset appears clean. No warnings detected.", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(5)

    # ── Strongest Numerical Relationships (Top 10)
    pdf.add_page()
    pdf.set_font("Helvetica", "B", H2)
    pdf.cell(0, 8, "Top Numerical Relationships", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)
    
    if data.relationships and data.relationships.pairs:
        pairs = sorted(data.relationships.pairs, key=lambda x: abs(x.pearson), reverse=True)[:10]
        
        # Table Header
        pdf.set_font("Helvetica", "B", 9)
        pdf.cell(50, 6, "Feature A", border=1)
        pdf.cell(50, 6, "Feature B", border=1)
        pdf.cell(30, 6, "Pearson", border=1)
        pdf.cell(30, 6, "Spearman", border=1)
        pdf.ln()
        
        pdf.set_font("Helvetica", "", 9)
        for p in pairs:
            # Truncate long names
            fa = p.feature_a[:20] + "..." if len(p.feature_a) > 23 else p.feature_a
            fb = p.feature_b[:20] + "..." if len(p.feature_b) > 23 else p.feature_b
            
            pdf.cell(50, 6, fa, border=1)
            pdf.cell(50, 6, fb, border=1)
            pdf.cell(30, 6, f"{p.pearson:.3f}", border=1)
            pdf.cell(30, 6, f"{p.spearman:.3f}", border=1)
            pdf.ln()
        
        if len(data.relationships.pairs) > 10:
            pdf.set_font("Helvetica", "I", 8)
            pdf.cell(0, 6, f"Showing top 10 results out of {len(data.relationships.pairs)} total pairs.", new_x="LMARGIN", new_y="NEXT")
    else:
        pdf.set_font("Helvetica", "I", BODY)
        pdf.cell(0, 6, "No relevant numerical findings.", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(8)
    
    # ── Strongest Categorical Relationships (Top 10)
    pdf.set_font("Helvetica", "B", H2)
    pdf.cell(0, 8, "Top Categorical Relationships", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)
    
    if data.categorical and (data.categorical.cat_cat_pairs or data.categorical.cat_num_pairs):
        # Combine and sort by score
        items = []
        for p in data.categorical.cat_cat_pairs:
            items.append(("Cat-Cat", p.feature_a, p.feature_b, "Cramer's V", p.cramers_v))
        for p in data.categorical.cat_num_pairs:
            items.append(("Cat-Num", p.categorical_feature, p.numerical_feature, "Eta-Squared", p.eta_squared))
            
        items.sort(key=lambda x: x[4], reverse=True)
        items = items[:10]
        
        # Table Header
        pdf.set_font("Helvetica", "B", 9)
        pdf.cell(30, 6, "Type", border=1)
        pdf.cell(45, 6, "Feature 1", border=1)
        pdf.cell(45, 6, "Feature 2", border=1)
        pdf.cell(40, 6, "Metric: Score", border=1)
        pdf.ln()
        
        pdf.set_font("Helvetica", "", 9)
        for it in items:
            t, f1, f2, met, sc = it
            f1 = f1[:18] + "..." if len(f1) > 21 else f1
            f2 = f2[:18] + "..." if len(f2) > 21 else f2
            
            pdf.cell(30, 6, t, border=1)
            pdf.cell(45, 6, f1, border=1)
            pdf.cell(45, 6, f2, border=1)
            pdf.cell(40, 6, f"{met}: {sc:.3f}", border=1)
            pdf.ln()
    else:
        pdf.set_font("Helvetica", "I", BODY)
        pdf.cell(0, 6, "No relevant categorical findings.", new_x="LMARGIN", new_y="NEXT")
        
    return pdf.output()
